### ISSUE TITLE
Feature request: Non-interactive picking of thing types

### ISSUE THREAD

**Issue by diamond-lizard** [AdrieanKhisbe/omni-kill.el#3]
In `omni-kill--generate-dispatch-command` type of thing to pick is prompted for interactively.  I'd like to request a non-interactive (scriptable) way of picking it and then passing the choice on.

The reason for this request is that I'd like to write a hydra that prompts me for all the different types of things that I can pick, and once I choose what I want using the hydra, I'd like to be able to pass that choice on so it can be acted on.

I'm not sure if the best way to do that would be to add a hook to `omni-kill--generate-dispatch-command` or parameterize it or maybe some other way.

**Comment by AdrieanKhisbe** [comment]
Hello @diamond-lizard :)
Thanks for your interest in omni-kill,

you could either give the char corresponding to the thing to the dispatch command: `(omni-kill "e")`, though that would not be much readable
Or you could use the generate functions, `omni-kill-email` and so on. (there is a command per action + thing)

Tell me if I misunderstood your question

**Comment by diamond-lizard** [comment]
This works great.  Thanks!

**Comment by AdrieanKhisbe** [comment]
great!
Shall I close the issue then? :)

**Comment by diamond-lizard** [comment]
That's at your discretion.  But I am satisfied with the already-existing features of omni-kill for this particular use case.

**Comment by AdrieanKhisbe** [comment]
Okey dokey, I'll close for now them. Buf if the needs come, feel free to do it again.
I'll keep it in mind, and maybe make `omni-kill` accept thing symbol as argument

**Comment by AdrieanKhisbe** [comment]
@diamond-lizard on second though was simple to implement so I added it.
So you can `(omni-copy 'email)` rather than `(omni-copy ?e)` 
Release v0.5.1 is there for you 😉

**Comment by diamond-lizard** [comment]
Thanks!
