### ISSUE TITLE
Eager macro-expansion failure: (void-variable action)

### ISSUE THREAD

**Issue by diamond-lizard** [AdrieanKhisbe/omni-kill.el#4]
`omni-kill.el` is causing Emacs to complain of `Eager macro-expansion failure: (void-variable action)`.

I've tracked this down to `omni-kill--generate-all-the-fun`, which calls `(omni-kill--generate-dispatch-command action)`.  The root cause, however, seems to be the `omni-kill--generate-dispatch-command` macro itself, which tries to `(eval command)` at compile time, while `command` only exists at runtime.

**Comment by AdrieanKhisbe** [comment]
@diamond-lizard Good thing you open an issue, 
I saw the byte compiled issue, but didn't find a work around at the time.
I couldn't get ride of the eval command.

I finally found a work around, by replacing the `defmacro` with `defun`, that bind a lambda closure to the symbol with `defalias`

Here is the refactor: ba04337
Tell me if it suits you, if so I'll make a minor release

**Comment by diamond-lizard** [comment]
This looks good.  No more error.  Thank you.
