### ISSUE TITLE
omni-kill vs thing-edit

### ISSUE THREAD

**Issue by seagle0128** [AdrieanKhisbe/omni-kill.el#5]
Hi, Actually it's not an issue. Recently I found this package is very similar with [thing-edit](https://github.com/manateelazycat/thing-edit) which is not in `melpa`. Could you please compare both and enhance `omni-kill`? Thanks.

**Comment by AdrieanKhisbe** [comment]
Hello @seagle0128,
sorry for the late answer.

I didn't know about *thing-edit*.
It seems to give access to similar functions than omni-kill to some extent,
Also, both are based on `thingatpt`

but I can also tell that:
- omni-kill is based on emacs defmacros: hence more easy to add **actions** or **things**
- omni-kill has dispatch action where you can first invoke a command stating the action you want to make (ex: kill), then prompt you for a char corresponding to the **thing** you want to act on.

**Comment by seagle0128** [comment]
Thanks for the reply!

**Comment by AdrieanKhisbe** [comment]
@seagle0128 you're welcome :)
Shall I close the issue?

**Comment by seagle0128** [comment]
Sure.
